version: "3.9"

services:
  backend:
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: supersecretkey123
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    networks:
      - appnet
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet
    restart: always
    # Если хочешь монтировать локальный nginx.conf вместо вшитого в образ — раскомментируй:
    # volumes:
    #   - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5
      start_period: 10s
    restart: always

networks:
  appnet:
    driver: bridge

volumes:
  db_data:

