"""add viewer role to userrole enum

Revision ID: ddf06ef0271c
Revises: 233ad4c31fd4
Create Date: 2025-09-26 17:08:41.871262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf06ef0271c'
down_revision: Union[str, None] = '233ad4c31fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
